services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    # ports:
    #   - 10.26.0.6:53:53    #So na rede principal
    volumes:
      - ./darthvader/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/db.192.168.20:/var/cache/bind/db.192.168.20
      - ./darthvader/db.starwars.lan:/var/cache/bind/db.starwars.lan
    networks:
      rededns:
        ipv4_address: 192.168.20.10
  darthsidious:
    build: dnsserver
    hostname: darthsidious
    #Quitámolos non sei por que vese que non fai falta
    # ports:
    #   - 10.26.0.6:53:53    #So na rede principal
    volumes:
      - ./darthsidious/named.conf.options:/etc/bind/named.conf.options
      - ./darthsidious/named.conf.local:/etc/bind/named.conf.local
    networks:
      rededns:
        ipv4_address: 192.168.20.11
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.100
    dns:
    - 192.168.20.10
    - 192.168.20.11
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24


