services:
  darthvader:
    build: dnsserver
    hostname: darthvader
    # ports:
    #   - 10.26.0.6:53:53    #So na rede principal
    volumes:
      - ./darthvader/named.conf.options:/etc/bind/named.conf.options
      - ./darthvader/named.conf.local:/etc/bind/named.conf.local
      - ./darthvader/db.192.168.20:/var/cache/bind/db.192.168.20
      - ./darthvader/db.starwars.lan:/var/cache/bind/db.starwars.lan
      - ./logs:/var/log/bind/
      - ./logs/query.log:/var/log/bind/query.log
      - ./logs/update.log:/var/log/bind/update.log
    networks:
      rededns:
        ipv4_address: 192.168.20.10
  darthsidious:
    build: dnsserver
    hostname: darthsidious
    depends_on:
      - darthvader
    #Quitámolos non sei por que vese que non fai falta
    # ports:
    #   - 10.26.0.6:53:53    #So na rede principal
    volumes:
      - ./darthsidious/named.conf.options:/etc/bind/named.conf.options
      - ./darthsidious/named.conf.local:/etc/bind/named.conf.local
    networks:
      rededns:
        ipv4_address: 192.168.20.11

  leia:
    build: dnsserver
    hostname: leia
    depends_on:
      - darthvader
    volumes:
      - ./leia/named.conf.options:/etc/bind/named.conf.options
      - ./leia/named.conf.local:/etc/bind/named.conf.local
      - ./leia/named.conf.local:/var/cache/bind/db.imperio.starwars.lan
    networks:
      rededns:
        ipv4_address: 192.168.20.106
  cliente:
    build: cliente
    hostname: cliente1
    networks:
      rededns:
        ipv4_address: 192.168.20.100
    volumes:
      - ./cliente/rndc.conf:/etc/bind/rndc.conf
      - ./cliente/chave.key:/etc/bind/chave.key
      - ./cliente/actualiza.txt:/etc/bind/actualiza.txt
    dns:
    - 192.168.20.10
    - 192.168.20.11
networks:
  rededns:
    ipam:
      config:
        - subnet: 192.168.20.0/24

